=== sisyphus-gamedev-studio/sisyphus-gamedev-studio.github.io/.astro/collections/projects.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "maximum": 9007199254740991
    },
    "image": {
      "type": "string",
      "pattern": "^\\/images\\/.*"
    },
    "video": {
      "anyOf": [
        {
          "type": "string",
          "pattern": "^\\/images\\/.*"
        },
        {
          "type": "object",
          "properties": {
            "en": {
              "type": "string",
              "pattern": "^\\/images\\/.*"
            },
            "ru": {
              "type": "string",
              "pattern": "^\\/images\\/.*"
            }
          },
          "required": [
            "en",
            "ru"
          ]
        }
      ]
    },
    "progress": {
      "type": "number",
      "minimum": 0,
      "maximum": 100
    },
    "wishlistUrl": {
      "type": "string",
      "format": "uri"
    },
    "en": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "price": {
          "type": "string",
          "minLength": 1
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "title",
        "description",
        "price"
      ]
    },
    "ru": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "price": {
          "type": "string",
          "minLength": 1
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "title",
        "description",
        "price"
      ]
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "image",
    "en",
    "ru"
  ]
}

=== sisyphus-gamedev-studio/sisyphus-gamedev-studio.github.io/src/content/projects/02.json
{
  "id": 2,
  "image": "/images/projects/project-2.jpg",
  "video": {
    "ru": "/images/video/KRINV1_720.mp4",
    "en": "/images/video/KRIV2_720.mp4"
  },
  "wishlistUrl": "https://store.steampowered.com/app/krivda",
  "en": {
    "title": "Krivda",
    "description": "A cooperative survival simulator steeped in the spirit of Slavic mythology. The open world is filled with secrets and dangers. To survive, you'll need to become one with nature and the spirit world, learn new things, and become stronger and more cunning.",
    "price": "Coming Soon",
    "tags": ["Co-op", "Survival", "Open World", "Slavic Mythology", "RPG", "Infinite Progression"]
  },
  "ru": {
    "title": "Кривда",
    "description": "Кооперативный симулятор выживания, пронизанный духом славянской мифологии. Открытый мир наполнен тайнами и опасностями, чтобы выжить — придется стать единым целым с природой и миром духов.",
    "price": "Скоро",
    "tags": [
      "Кооп",
      "Выживание",
      "Открытый мир",
      "Слав. мифология",
      "RPG",
      "Бесконечная прогрессия"
    ]
  }
}

=== sisyphus-gamedev-studio/sisyphus-gamedev-studio.github.io/src/content/projects/01.json
{
  "id": 1,
  "image": "/images/projects/project-1.jpg",
  "progress": 5,
  "wishlistUrl": "https://store.steampowered.com/app/frogfrag",
  "en": {
    "title": "Frog Frag",
    "description": "A cooperative shooter, a deathmatch. Each battle is unique thanks to a randomly generated map. Mix and match weapons, creating even the most absurd and ridiculous combinations.",
    "price": "In Development",
    "tags": ["Co-op", "Shooter", "Deathmatch", "Roguelite", "FPS"]
  },
  "ru": {
    "title": "Frog Frag",
    "description": "Кооперативный шутер, бой на смерть. Каждая схватка будет уникальна за счет случайно созданной карты. Скрещивай оружие, создавая даже самые абсурдные и нелепые сочетания.",
    "price": "В разработке",
    "tags": ["Кооп", "Шутер", "Бой на смерть", "Рогалик", "FPS"]
  }
}
